-- Team- and league-level season aggregates (SPEC follow-up). Live views that
-- sum player_match_stats by team / by competition-season; per-match = total /
-- matches_played. Includes distance-band shot/goal counts for long-range analysis.

CREATE OR REPLACE VIEW team_season_stats AS
SELECT
  m.competition_id,
  m.season_id,
  pms.team_id,
  COUNT(DISTINCT pms.match_id) AS matches_played,
  SUM(pms.goals) AS goals,
  SUM(pms.assists) AS assists,
  SUM(pms.npg) AS npg,
  SUM(pms.npxg) AS npxg,
  SUM(pms.xa) AS xa,
  SUM(pms.npxg_plus_xa) AS npxg_plus_xa,
  SUM(pms.shots) AS shots,
  SUM(pms.shots_on_target) AS shots_on_target,
  SUM(pms.passes_attempted) AS passes_attempted,
  SUM(pms.passes_completed) AS passes_completed,
  SUM(pms.progressive_passes) AS progressive_passes,
  SUM(pms.progressive_passes_received) AS progressive_passes_received,
  SUM(pms.successful_take_ons) AS successful_take_ons,
  SUM(pms.take_ons_attempted) AS take_ons_attempted,
  SUM(pms.progressive_carries) AS progressive_carries,
  SUM(pms.touches_in_att_pen_area) AS touches_in_att_pen_area,
  SUM(pms.tackles) AS tackles,
  SUM(pms.interceptions) AS interceptions,
  SUM(pms.blocks) AS blocks,
  SUM(pms.clearances) AS clearances,
  SUM(pms.aerials_won) AS aerials_won,
  SUM(pms.aerials_lost) AS aerials_lost,
  SUM(pms.fouls_drawn) AS fouls_drawn,
  SUM(pms.ball_recoveries) AS ball_recoveries,
  SUM(pms.sca) AS sca,
  SUM(pms.gca) AS gca,
  SUM(pms.key_passes) AS key_passes,
  SUM(pms.through_balls_attempted) AS through_balls_attempted,
  SUM(pms.through_balls_completed) AS through_balls_completed,
  SUM(pms.crosses_attempted) AS crosses_attempted,
  SUM(pms.crosses_completed) AS crosses_completed,
  SUM(pms.passes_into_final_third) AS passes_into_final_third,
  SUM(pms.passes_into_box) AS passes_into_box,
  SUM(pms.long_balls_attempted) AS long_balls_attempted,
  SUM(pms.long_balls_completed) AS long_balls_completed,
  SUM(pms.big_chances_created) AS big_chances_created,
  SUM(pms.carries_into_final_third) AS carries_into_final_third,
  SUM(pms.carries_into_box) AS carries_into_box,
  SUM(pms.carry_distance) AS carry_distance,
  SUM(pms.progressive_carry_distance) AS progressive_carry_distance,
  SUM(pms.miscontrols) AS miscontrols,
  SUM(pms.dispossessed) AS dispossessed,
  SUM(pms.shot_distance_sum) AS shot_distance_sum,
  SUM(pms.shots_outside_box) AS shots_outside_box,
  SUM(pms.goals_outside_box) AS goals_outside_box,
  SUM(pms.shots_long_range) AS shots_long_range,
  SUM(pms.goals_long_range) AS goals_long_range,
  SUM(pms.big_chances_faced) AS big_chances_faced,
  SUM(pms.big_chances_scored) AS big_chances_scored,
  SUM(pms.tackles_won) AS tackles_won,
  SUM(pms.tackles_def_third) AS tackles_def_third,
  SUM(pms.tackles_mid_third) AS tackles_mid_third,
  SUM(pms.tackles_att_third) AS tackles_att_third,
  SUM(pms.dribbled_past) AS dribbled_past,
  SUM(pms.errors_leading_to_shot) AS errors_leading_to_shot,
  SUM(pms.xa_open_play) AS xa_open_play,
  SUM(pms.xa_set_piece) AS xa_set_piece,
  SUM(pms.xt) AS xt,
  SUM(pms.xt_pass) AS xt_pass,
  SUM(pms.xt_carry) AS xt_carry,
  SUM(pms.xg_chain) AS xg_chain,
  SUM(pms.xg_buildup) AS xg_buildup,
  SUM(pms.passes_completed)::numeric / NULLIF(SUM(pms.passes_attempted),0) * 100 AS pass_completion_pct
FROM player_match_stats pms
JOIN matches m ON m.id = pms.match_id
GROUP BY m.competition_id, m.season_id, pms.team_id;

CREATE OR REPLACE VIEW league_season_stats AS
SELECT
  m.competition_id,
  m.season_id,
  COUNT(DISTINCT pms.match_id) AS matches_played,
  COUNT(DISTINCT pms.team_id) AS teams,
  SUM(pms.goals) AS goals,
  SUM(pms.assists) AS assists,
  SUM(pms.npg) AS npg,
  SUM(pms.npxg) AS npxg,
  SUM(pms.xa) AS xa,
  SUM(pms.npxg_plus_xa) AS npxg_plus_xa,
  SUM(pms.shots) AS shots,
  SUM(pms.shots_on_target) AS shots_on_target,
  SUM(pms.passes_attempted) AS passes_attempted,
  SUM(pms.passes_completed) AS passes_completed,
  SUM(pms.progressive_passes) AS progressive_passes,
  SUM(pms.progressive_passes_received) AS progressive_passes_received,
  SUM(pms.successful_take_ons) AS successful_take_ons,
  SUM(pms.take_ons_attempted) AS take_ons_attempted,
  SUM(pms.progressive_carries) AS progressive_carries,
  SUM(pms.touches_in_att_pen_area) AS touches_in_att_pen_area,
  SUM(pms.tackles) AS tackles,
  SUM(pms.interceptions) AS interceptions,
  SUM(pms.blocks) AS blocks,
  SUM(pms.clearances) AS clearances,
  SUM(pms.aerials_won) AS aerials_won,
  SUM(pms.aerials_lost) AS aerials_lost,
  SUM(pms.fouls_drawn) AS fouls_drawn,
  SUM(pms.ball_recoveries) AS ball_recoveries,
  SUM(pms.sca) AS sca,
  SUM(pms.gca) AS gca,
  SUM(pms.key_passes) AS key_passes,
  SUM(pms.through_balls_attempted) AS through_balls_attempted,
  SUM(pms.through_balls_completed) AS through_balls_completed,
  SUM(pms.crosses_attempted) AS crosses_attempted,
  SUM(pms.crosses_completed) AS crosses_completed,
  SUM(pms.passes_into_final_third) AS passes_into_final_third,
  SUM(pms.passes_into_box) AS passes_into_box,
  SUM(pms.long_balls_attempted) AS long_balls_attempted,
  SUM(pms.long_balls_completed) AS long_balls_completed,
  SUM(pms.big_chances_created) AS big_chances_created,
  SUM(pms.carries_into_final_third) AS carries_into_final_third,
  SUM(pms.carries_into_box) AS carries_into_box,
  SUM(pms.carry_distance) AS carry_distance,
  SUM(pms.progressive_carry_distance) AS progressive_carry_distance,
  SUM(pms.miscontrols) AS miscontrols,
  SUM(pms.dispossessed) AS dispossessed,
  SUM(pms.shot_distance_sum) AS shot_distance_sum,
  SUM(pms.shots_outside_box) AS shots_outside_box,
  SUM(pms.goals_outside_box) AS goals_outside_box,
  SUM(pms.shots_long_range) AS shots_long_range,
  SUM(pms.goals_long_range) AS goals_long_range,
  SUM(pms.big_chances_faced) AS big_chances_faced,
  SUM(pms.big_chances_scored) AS big_chances_scored,
  SUM(pms.tackles_won) AS tackles_won,
  SUM(pms.tackles_def_third) AS tackles_def_third,
  SUM(pms.tackles_mid_third) AS tackles_mid_third,
  SUM(pms.tackles_att_third) AS tackles_att_third,
  SUM(pms.dribbled_past) AS dribbled_past,
  SUM(pms.errors_leading_to_shot) AS errors_leading_to_shot,
  SUM(pms.xa_open_play) AS xa_open_play,
  SUM(pms.xa_set_piece) AS xa_set_piece,
  SUM(pms.xt) AS xt,
  SUM(pms.xt_pass) AS xt_pass,
  SUM(pms.xt_carry) AS xt_carry,
  SUM(pms.xg_chain) AS xg_chain,
  SUM(pms.xg_buildup) AS xg_buildup,
  SUM(pms.passes_completed)::numeric / NULLIF(SUM(pms.passes_attempted),0) * 100 AS pass_completion_pct
FROM player_match_stats pms
JOIN matches m ON m.id = pms.match_id
GROUP BY m.competition_id, m.season_id;
