-- npxG split open-play vs set-piece (player, team, league).
-- Adds match/season columns + regenerates the three aggregate views to include
-- npxg_open_play / npxg_set_piece. Back-populated by reprocess.

ALTER TABLE player_match_stats
  ADD COLUMN npxg_open_play NUMERIC,
  ADD COLUMN npxg_set_piece NUMERIC;

ALTER TABLE player_season_stats
  ADD COLUMN npxg_open_play_p90 NUMERIC,
  ADD COLUMN npxg_set_piece_p90 NUMERIC;

DROP VIEW IF EXISTS player_season_percentiles;
CREATE VIEW player_season_percentiles AS
SELECT
  pss.player_id,
  pss.season_id,
  pss.position_bucket,
  pss.minutes,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npg_p90) * 100 AS npg_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npxg_p90) * 100 AS npxg_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.shots_p90) * 100 AS shots_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.assists_p90) * 100 AS assists_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xa_p90) * 100 AS xa_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npxg_plus_xa_p90) * 100 AS npxg_plus_xa_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.sca_p90) * 100 AS sca_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.gca_p90) * 100 AS gca_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.passes_attempted_p90) * 100 AS passes_attempted_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.pass_completion_pct) * 100 AS pass_completion_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.progressive_passes_p90) * 100 AS progressive_passes_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.progressive_passes_received_p90) * 100 AS progressive_passes_received_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.successful_take_ons_p90) * 100 AS successful_take_ons_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.take_on_success_pct) * 100 AS take_on_success_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.progressive_carries_p90) * 100 AS progressive_carries_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.touches_in_att_pen_area_p90) * 100 AS touches_in_att_pen_area_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.tackles_p90) * 100 AS tackles_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.interceptions_p90) * 100 AS interceptions_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.blocks_p90) * 100 AS blocks_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.clearances_p90) * 100 AS clearances_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.aerials_won_pct) * 100 AS aerials_won_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.fouls_drawn_p90) * 100 AS fouls_drawn_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.ball_recoveries_p90) * 100 AS ball_recoveries_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.shots_on_target_p90) * 100 AS shots_on_target_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.key_passes_p90) * 100 AS key_passes_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.through_balls_p90) * 100 AS through_balls_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.through_ball_completion_pct) * 100 AS through_ball_completion_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.crosses_p90) * 100 AS crosses_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.cross_completion_pct) * 100 AS cross_completion_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.passes_into_final_third_p90) * 100 AS passes_into_final_third_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.passes_into_box_p90) * 100 AS passes_into_box_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.long_balls_p90) * 100 AS long_balls_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.long_ball_completion_pct) * 100 AS long_ball_completion_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.big_chances_created_p90) * 100 AS big_chances_created_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.carries_into_final_third_p90) * 100 AS carries_into_final_third_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.carries_into_box_p90) * 100 AS carries_into_box_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.carry_distance_p90) * 100 AS carry_distance_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.progressive_carry_distance_p90) * 100 AS progressive_carry_distance_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.miscontrols_p90) * 100 AS miscontrols_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.dispossessed_p90) * 100 AS dispossessed_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.shots_on_target_pct) * 100 AS shots_on_target_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npxg_per_shot) * 100 AS npxg_per_shot_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.avg_shot_distance) * 100 AS avg_shot_distance_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.np_g_minus_xg) * 100 AS np_g_minus_xg_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.big_chances_faced_p90) * 100 AS big_chances_faced_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.big_chance_conversion_pct) * 100 AS big_chance_conversion_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.tackle_win_pct) * 100 AS tackle_win_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.tackles_def_third_p90) * 100 AS tackles_def_third_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.tackles_mid_third_p90) * 100 AS tackles_mid_third_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.tackles_att_third_p90) * 100 AS tackles_att_third_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.dribbled_past_p90) * 100 AS dribbled_past_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.errors_leading_to_shot_p90) * 100 AS errors_leading_to_shot_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xa_open_play_p90) * 100 AS xa_open_play_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xa_set_piece_p90) * 100 AS xa_set_piece_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xt_p90) * 100 AS xt_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xt_pass_p90) * 100 AS xt_pass_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xt_carry_p90) * 100 AS xt_carry_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xg_chain_p90) * 100 AS xg_chain_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xg_buildup_p90) * 100 AS xg_buildup_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npxg_open_play_p90) * 100 AS npxg_open_play_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npxg_set_piece_p90) * 100 AS npxg_set_piece_p90_pct
FROM player_season_stats pss
WHERE pss.minutes >= (
  SELECT pc.minutes_threshold FROM percentile_config pc WHERE pc.season_id = pss.season_id
);

DROP VIEW IF EXISTS team_season_stats;
CREATE VIEW team_season_stats AS
SELECT
  m.competition_id,
  m.season_id,
  pms.team_id,
  COUNT(DISTINCT pms.match_id) AS matches_played,
  SUM(pms.goals) AS goals,
  SUM(pms.assists) AS assists,
  SUM(pms.npg) AS npg,
  SUM(pms.npxg) AS npxg,
  SUM(pms.xa) AS xa,
  SUM(pms.npxg_plus_xa) AS npxg_plus_xa,
  SUM(pms.shots) AS shots,
  SUM(pms.shots_on_target) AS shots_on_target,
  SUM(pms.passes_attempted) AS passes_attempted,
  SUM(pms.passes_completed) AS passes_completed,
  SUM(pms.progressive_passes) AS progressive_passes,
  SUM(pms.progressive_passes_received) AS progressive_passes_received,
  SUM(pms.successful_take_ons) AS successful_take_ons,
  SUM(pms.take_ons_attempted) AS take_ons_attempted,
  SUM(pms.progressive_carries) AS progressive_carries,
  SUM(pms.touches_in_att_pen_area) AS touches_in_att_pen_area,
  SUM(pms.tackles) AS tackles,
  SUM(pms.interceptions) AS interceptions,
  SUM(pms.blocks) AS blocks,
  SUM(pms.clearances) AS clearances,
  SUM(pms.aerials_won) AS aerials_won,
  SUM(pms.aerials_lost) AS aerials_lost,
  SUM(pms.fouls_drawn) AS fouls_drawn,
  SUM(pms.ball_recoveries) AS ball_recoveries,
  SUM(pms.sca) AS sca,
  SUM(pms.gca) AS gca,
  SUM(pms.key_passes) AS key_passes,
  SUM(pms.through_balls_attempted) AS through_balls_attempted,
  SUM(pms.through_balls_completed) AS through_balls_completed,
  SUM(pms.crosses_attempted) AS crosses_attempted,
  SUM(pms.crosses_completed) AS crosses_completed,
  SUM(pms.passes_into_final_third) AS passes_into_final_third,
  SUM(pms.passes_into_box) AS passes_into_box,
  SUM(pms.long_balls_attempted) AS long_balls_attempted,
  SUM(pms.long_balls_completed) AS long_balls_completed,
  SUM(pms.big_chances_created) AS big_chances_created,
  SUM(pms.carries_into_final_third) AS carries_into_final_third,
  SUM(pms.carries_into_box) AS carries_into_box,
  SUM(pms.carry_distance) AS carry_distance,
  SUM(pms.progressive_carry_distance) AS progressive_carry_distance,
  SUM(pms.miscontrols) AS miscontrols,
  SUM(pms.dispossessed) AS dispossessed,
  SUM(pms.shot_distance_sum) AS shot_distance_sum,
  SUM(pms.shots_outside_box) AS shots_outside_box,
  SUM(pms.goals_outside_box) AS goals_outside_box,
  SUM(pms.shots_long_range) AS shots_long_range,
  SUM(pms.goals_long_range) AS goals_long_range,
  SUM(pms.big_chances_faced) AS big_chances_faced,
  SUM(pms.big_chances_scored) AS big_chances_scored,
  SUM(pms.tackles_won) AS tackles_won,
  SUM(pms.tackles_def_third) AS tackles_def_third,
  SUM(pms.tackles_mid_third) AS tackles_mid_third,
  SUM(pms.tackles_att_third) AS tackles_att_third,
  SUM(pms.dribbled_past) AS dribbled_past,
  SUM(pms.errors_leading_to_shot) AS errors_leading_to_shot,
  SUM(pms.xa_open_play) AS xa_open_play,
  SUM(pms.xa_set_piece) AS xa_set_piece,
  SUM(pms.xt) AS xt,
  SUM(pms.xt_pass) AS xt_pass,
  SUM(pms.xt_carry) AS xt_carry,
  SUM(pms.xg_chain) AS xg_chain,
  SUM(pms.xg_buildup) AS xg_buildup,
  SUM(pms.npxg_open_play) AS npxg_open_play,
  SUM(pms.npxg_set_piece) AS npxg_set_piece,
  SUM(pms.passes_completed)::numeric / NULLIF(SUM(pms.passes_attempted),0) * 100 AS pass_completion_pct
FROM player_match_stats pms
JOIN matches m ON m.id = pms.match_id
GROUP BY m.competition_id, m.season_id, pms.team_id;

DROP VIEW IF EXISTS league_season_stats;
CREATE VIEW league_season_stats AS
SELECT
  m.competition_id,
  m.season_id,
  COUNT(DISTINCT pms.match_id) AS matches_played,
  COUNT(DISTINCT pms.team_id) AS teams,
  SUM(pms.goals) AS goals,
  SUM(pms.assists) AS assists,
  SUM(pms.npg) AS npg,
  SUM(pms.npxg) AS npxg,
  SUM(pms.xa) AS xa,
  SUM(pms.npxg_plus_xa) AS npxg_plus_xa,
  SUM(pms.shots) AS shots,
  SUM(pms.shots_on_target) AS shots_on_target,
  SUM(pms.passes_attempted) AS passes_attempted,
  SUM(pms.passes_completed) AS passes_completed,
  SUM(pms.progressive_passes) AS progressive_passes,
  SUM(pms.progressive_passes_received) AS progressive_passes_received,
  SUM(pms.successful_take_ons) AS successful_take_ons,
  SUM(pms.take_ons_attempted) AS take_ons_attempted,
  SUM(pms.progressive_carries) AS progressive_carries,
  SUM(pms.touches_in_att_pen_area) AS touches_in_att_pen_area,
  SUM(pms.tackles) AS tackles,
  SUM(pms.interceptions) AS interceptions,
  SUM(pms.blocks) AS blocks,
  SUM(pms.clearances) AS clearances,
  SUM(pms.aerials_won) AS aerials_won,
  SUM(pms.aerials_lost) AS aerials_lost,
  SUM(pms.fouls_drawn) AS fouls_drawn,
  SUM(pms.ball_recoveries) AS ball_recoveries,
  SUM(pms.sca) AS sca,
  SUM(pms.gca) AS gca,
  SUM(pms.key_passes) AS key_passes,
  SUM(pms.through_balls_attempted) AS through_balls_attempted,
  SUM(pms.through_balls_completed) AS through_balls_completed,
  SUM(pms.crosses_attempted) AS crosses_attempted,
  SUM(pms.crosses_completed) AS crosses_completed,
  SUM(pms.passes_into_final_third) AS passes_into_final_third,
  SUM(pms.passes_into_box) AS passes_into_box,
  SUM(pms.long_balls_attempted) AS long_balls_attempted,
  SUM(pms.long_balls_completed) AS long_balls_completed,
  SUM(pms.big_chances_created) AS big_chances_created,
  SUM(pms.carries_into_final_third) AS carries_into_final_third,
  SUM(pms.carries_into_box) AS carries_into_box,
  SUM(pms.carry_distance) AS carry_distance,
  SUM(pms.progressive_carry_distance) AS progressive_carry_distance,
  SUM(pms.miscontrols) AS miscontrols,
  SUM(pms.dispossessed) AS dispossessed,
  SUM(pms.shot_distance_sum) AS shot_distance_sum,
  SUM(pms.shots_outside_box) AS shots_outside_box,
  SUM(pms.goals_outside_box) AS goals_outside_box,
  SUM(pms.shots_long_range) AS shots_long_range,
  SUM(pms.goals_long_range) AS goals_long_range,
  SUM(pms.big_chances_faced) AS big_chances_faced,
  SUM(pms.big_chances_scored) AS big_chances_scored,
  SUM(pms.tackles_won) AS tackles_won,
  SUM(pms.tackles_def_third) AS tackles_def_third,
  SUM(pms.tackles_mid_third) AS tackles_mid_third,
  SUM(pms.tackles_att_third) AS tackles_att_third,
  SUM(pms.dribbled_past) AS dribbled_past,
  SUM(pms.errors_leading_to_shot) AS errors_leading_to_shot,
  SUM(pms.xa_open_play) AS xa_open_play,
  SUM(pms.xa_set_piece) AS xa_set_piece,
  SUM(pms.xt) AS xt,
  SUM(pms.xt_pass) AS xt_pass,
  SUM(pms.xt_carry) AS xt_carry,
  SUM(pms.xg_chain) AS xg_chain,
  SUM(pms.xg_buildup) AS xg_buildup,
  SUM(pms.npxg_open_play) AS npxg_open_play,
  SUM(pms.npxg_set_piece) AS npxg_set_piece,
  SUM(pms.passes_completed)::numeric / NULLIF(SUM(pms.passes_attempted),0) * 100 AS pass_completion_pct
FROM player_match_stats pms
JOIN matches m ON m.id = pms.match_id
GROUP BY m.competition_id, m.season_id;
