-- Initial schema migration
-- Creates all tables for the football scouting dashboard.
-- Do not edit this file after it has been applied. Add new migrations instead.

-- Competitions
CREATE TABLE competitions (
  id INT PRIMARY KEY,              -- WhoScored competition id
  name TEXT NOT NULL,
  country TEXT NOT NULL
);

-- Seasons
CREATE TABLE seasons (
  id SERIAL PRIMARY KEY,
  competition_id INT NOT NULL REFERENCES competitions(id),
  season_label TEXT NOT NULL,      -- e.g. '2025-2026'
  UNIQUE (competition_id, season_label)
);

-- Teams
CREATE TABLE teams (
  id INT PRIMARY KEY,              -- WhoScored team id
  name TEXT NOT NULL,
  short_name TEXT,
  country TEXT
);

-- Players
CREATE TABLE players (
  id INT PRIMARY KEY,              -- WhoScored player id
  name TEXT NOT NULL,
  birth_date DATE,
  nationality TEXT,
  preferred_foot TEXT,
  height_cm INT
);

-- Matches
CREATE TABLE matches (
  id BIGINT PRIMARY KEY,           -- WhoScored match id
  competition_id INT NOT NULL REFERENCES competitions(id),
  season_id INT NOT NULL REFERENCES seasons(id),
  kickoff TIMESTAMPTZ NOT NULL,
  home_team_id INT NOT NULL REFERENCES teams(id),
  away_team_id INT NOT NULL REFERENCES teams(id),
  home_score INT,
  away_score INT,
  status TEXT NOT NULL,            -- 'finished', 'scheduled', 'postponed'
  raw_json_path TEXT,              -- path in Supabase Storage
  ingested_at TIMESTAMPTZ
);

-- Player match stats (one row per player per match; raw counts, not per-90)
CREATE TABLE player_match_stats (
  id BIGSERIAL PRIMARY KEY,
  match_id BIGINT NOT NULL REFERENCES matches(id),
  player_id INT NOT NULL REFERENCES players(id),
  team_id INT NOT NULL REFERENCES teams(id),
  position_played TEXT NOT NULL,   -- WhoScored code: GK, DC, DL, DR, etc.
  position_bucket TEXT NOT NULL,   -- our taxonomy: GK, CB, FB, DM, CM, AM, W, CF
  minutes INT NOT NULL,
  goals INT,
  assists INT,
  npg INT,
  npxg NUMERIC,
  xa NUMERIC,
  npxg_plus_xa NUMERIC,
  shots INT,
  shots_on_target INT,
  passes_attempted INT,
  passes_completed INT,
  progressive_passes INT,
  progressive_passes_received INT,
  successful_take_ons INT,
  take_ons_attempted INT,
  progressive_carries INT,
  touches_in_att_pen_area INT,
  tackles INT,
  interceptions INT,
  blocks INT,
  clearances INT,
  aerials_won INT,
  aerials_lost INT,
  fouls_drawn INT,
  ball_recoveries INT,
  sca INT,
  gca INT,
  UNIQUE (match_id, player_id)
);

-- Player season stats (aggregated; per-90 computed here)
CREATE TABLE player_season_stats (
  id BIGSERIAL PRIMARY KEY,
  season_id INT NOT NULL REFERENCES seasons(id),
  player_id INT NOT NULL REFERENCES players(id),
  position_bucket TEXT NOT NULL,
  minutes INT NOT NULL,
  goals_p90 NUMERIC,
  assists_p90 NUMERIC,
  npg_p90 NUMERIC,
  npxg_p90 NUMERIC,
  xa_p90 NUMERIC,
  npxg_plus_xa_p90 NUMERIC,
  shots_p90 NUMERIC,
  shots_on_target_p90 NUMERIC,
  passes_attempted_p90 NUMERIC,
  pass_completion_pct NUMERIC,
  progressive_passes_p90 NUMERIC,
  progressive_passes_received_p90 NUMERIC,
  successful_take_ons_p90 NUMERIC,
  take_on_success_pct NUMERIC,
  progressive_carries_p90 NUMERIC,
  touches_in_att_pen_area_p90 NUMERIC,
  tackles_p90 NUMERIC,
  interceptions_p90 NUMERIC,
  blocks_p90 NUMERIC,
  clearances_p90 NUMERIC,
  aerials_won_pct NUMERIC,
  fouls_drawn_p90 NUMERIC,
  ball_recoveries_p90 NUMERIC,
  sca_p90 NUMERIC,
  gca_p90 NUMERIC,
  last_updated TIMESTAMPTZ DEFAULT now(),
  UNIQUE (season_id, player_id, position_bucket)
);

CREATE INDEX idx_pss_season_position ON player_season_stats (season_id, position_bucket);
CREATE INDEX idx_pms_match ON player_match_stats (match_id);
CREATE INDEX idx_pms_player ON player_match_stats (player_id);

-- Percentile threshold config (one row per season/competition; tweakable without code change)
CREATE TABLE percentile_config (
  id SERIAL PRIMARY KEY,
  season_id INT NOT NULL REFERENCES seasons(id),
  minutes_threshold INT NOT NULL,
  UNIQUE (season_id)
);

-- Percentile view (PERCENT_RANK over same season + position bucket)
CREATE OR REPLACE VIEW player_season_percentiles AS
SELECT
  pss.player_id,
  pss.season_id,
  pss.position_bucket,
  pss.minutes,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npg_p90)                        * 100 AS npg_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npxg_p90)                       * 100 AS npxg_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.shots_p90)                      * 100 AS shots_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.assists_p90)                    * 100 AS assists_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.xa_p90)                         * 100 AS xa_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.npxg_plus_xa_p90)               * 100 AS npxg_plus_xa_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.sca_p90)                        * 100 AS sca_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.gca_p90)                        * 100 AS gca_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.passes_attempted_p90)           * 100 AS passes_attempted_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.pass_completion_pct)            * 100 AS pass_completion_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.progressive_passes_p90)         * 100 AS progressive_passes_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.progressive_passes_received_p90)* 100 AS progressive_passes_received_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.successful_take_ons_p90)        * 100 AS successful_take_ons_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.take_on_success_pct)            * 100 AS take_on_success_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.progressive_carries_p90)        * 100 AS progressive_carries_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.touches_in_att_pen_area_p90)    * 100 AS touches_in_att_pen_area_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.tackles_p90)                    * 100 AS tackles_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.interceptions_p90)              * 100 AS interceptions_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.blocks_p90)                     * 100 AS blocks_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.clearances_p90)                 * 100 AS clearances_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.aerials_won_pct)                * 100 AS aerials_won_pct_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.fouls_drawn_p90)                * 100 AS fouls_drawn_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.ball_recoveries_p90)            * 100 AS ball_recoveries_p90_pct,
  PERCENT_RANK() OVER (PARTITION BY pss.season_id, pss.position_bucket ORDER BY pss.shots_on_target_p90)            * 100 AS shots_on_target_p90_pct
FROM player_season_stats pss
WHERE pss.minutes >= (
  SELECT pc.minutes_threshold
  FROM percentile_config pc
  WHERE pc.season_id = pss.season_id
);

-- Seed: 8 in-scope competitions
-- IDs are WhoScored tournament IDs, verified empirically 2026-06-01.
INSERT INTO competitions (id, name, country) VALUES
  (2,  'Premier League',        'England'),
  (4,  'La Liga',               'Spain'),
  (3,  'Bundesliga',            'Germany'),
  (5,  'Serie A',               'Italy'),
  (22, 'Ligue 1',               'France'),
  (13, 'Eredivisie',            'Netherlands'),
  (21, 'Primeira Liga',         'Portugal'),
  (12, 'UEFA Champions League', 'Europe');
