-- v2 metrics (SPEC §8.4): passing/creation depth, carrying detail, shooting
-- quality, defending detail, xA open/set-piece split, xT, and xGChain/xGBuildup.
-- Additive only. Back-populated by reprocessing stored JSONs (scripts/reprocess.py)
-- then re-rolling-up seasons (scripts/aggregate_season.py --all).

-- ---- match-level raw counts / sums --------------------------------------
ALTER TABLE player_match_stats
  ADD COLUMN key_passes INT,
  ADD COLUMN through_balls_attempted INT,
  ADD COLUMN through_balls_completed INT,
  ADD COLUMN crosses_attempted INT,
  ADD COLUMN crosses_completed INT,
  ADD COLUMN passes_into_final_third INT,
  ADD COLUMN passes_into_box INT,
  ADD COLUMN long_balls_attempted INT,
  ADD COLUMN long_balls_completed INT,
  ADD COLUMN big_chances_created INT,
  ADD COLUMN carries_into_final_third INT,
  ADD COLUMN carries_into_box INT,
  ADD COLUMN carry_distance NUMERIC,
  ADD COLUMN progressive_carry_distance NUMERIC,
  ADD COLUMN miscontrols INT,
  ADD COLUMN dispossessed INT,
  ADD COLUMN shot_distance_sum NUMERIC,
  ADD COLUMN big_chances_faced INT,
  ADD COLUMN big_chances_scored INT,
  ADD COLUMN tackles_won INT,
  ADD COLUMN tackles_def_third INT,
  ADD COLUMN tackles_mid_third INT,
  ADD COLUMN tackles_att_third INT,
  ADD COLUMN dribbled_past INT,
  ADD COLUMN errors_leading_to_shot INT,
  ADD COLUMN xa_open_play NUMERIC,
  ADD COLUMN xa_set_piece NUMERIC,
  ADD COLUMN xt NUMERIC,
  ADD COLUMN xt_pass NUMERIC,
  ADD COLUMN xt_carry NUMERIC,
  ADD COLUMN xg_chain NUMERIC,
  ADD COLUMN xg_buildup NUMERIC;

-- ---- season-level per-90s / ratios / differences ------------------------
ALTER TABLE player_season_stats
  ADD COLUMN key_passes_p90 NUMERIC,
  ADD COLUMN through_balls_p90 NUMERIC,
  ADD COLUMN through_ball_completion_pct NUMERIC,
  ADD COLUMN crosses_p90 NUMERIC,
  ADD COLUMN cross_completion_pct NUMERIC,
  ADD COLUMN passes_into_final_third_p90 NUMERIC,
  ADD COLUMN passes_into_box_p90 NUMERIC,
  ADD COLUMN long_balls_p90 NUMERIC,
  ADD COLUMN long_ball_completion_pct NUMERIC,
  ADD COLUMN big_chances_created_p90 NUMERIC,
  ADD COLUMN carries_into_final_third_p90 NUMERIC,
  ADD COLUMN carries_into_box_p90 NUMERIC,
  ADD COLUMN carry_distance_p90 NUMERIC,
  ADD COLUMN progressive_carry_distance_p90 NUMERIC,
  ADD COLUMN miscontrols_p90 NUMERIC,
  ADD COLUMN dispossessed_p90 NUMERIC,
  ADD COLUMN shots_on_target_pct NUMERIC,
  ADD COLUMN npxg_per_shot NUMERIC,
  ADD COLUMN avg_shot_distance NUMERIC,
  ADD COLUMN np_g_minus_xg NUMERIC,
  ADD COLUMN big_chances_faced_p90 NUMERIC,
  ADD COLUMN big_chance_conversion_pct NUMERIC,
  ADD COLUMN tackle_win_pct NUMERIC,
  ADD COLUMN tackles_def_third_p90 NUMERIC,
  ADD COLUMN tackles_mid_third_p90 NUMERIC,
  ADD COLUMN tackles_att_third_p90 NUMERIC,
  ADD COLUMN dribbled_past_p90 NUMERIC,
  ADD COLUMN errors_leading_to_shot_p90 NUMERIC,
  ADD COLUMN xa_open_play_p90 NUMERIC,
  ADD COLUMN xa_set_piece_p90 NUMERIC,
  ADD COLUMN xt_p90 NUMERIC,
  ADD COLUMN xt_pass_p90 NUMERIC,
  ADD COLUMN xt_carry_p90 NUMERIC,
  ADD COLUMN xg_chain_p90 NUMERIC,
  ADD COLUMN xg_buildup_p90 NUMERIC;
