# ruff: noqa: E501
"""GENERATED by scripts/train_production_xg.py — do not edit by hand.

Logistic xG coefficients fit by regression on Understat xG.
Trained 2026-06-02 on 43605 non-penalty shots (1751 matches, leagues ['Bundesliga', 'EPL', 'La_liga', 'Ligue_1', 'Serie_A']).
CV: per-shot R^2=0.650, per-player Spearman=0.939.
"""

FEATURE_NAMES = ['distance', 'distance_sq', 'angle', 'angle_sq', 'dist_angle', 'is_head', 'sit_corner', 'sit_setpiece', 'sit_dfk', 'la_throughball', 'la_cross', 'la_chipped', 'la_headpass']

MEANS = [17.654825, 393.655197, 0.433759, 0.260788, 5.977165, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

STDS = [9.053306, 616.162476, 0.26952, 0.426104, 1.035017, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

WEIGHTS = [-0.844323, -0.11173, 0.726097, -0.175631, -0.022887, -0.8955, -0.729148, -0.347557, 0.681185, 1.007094, -0.035281, 0.20463, -0.144315]

BIAS = -2.244212
