"""Expected Threat (xT) — runtime tagger (SPEC §8.4.1).

A possession-value grid (fit on our own events by scripts/fit_xt.py, stored in
the generated module ``xt_grid``) assigns each pitch cell a value. A player's xT
from an action is value(end_cell) − value(start_cell), summed over their
successful open-play passes and carries.

Grid orientation matches our events: attack toward x=100, so the highest-value
cells sit by the opponent goal.
"""

from ._qualifiers import get_qualifier
from .carries import _derive_carries

COLS = 16  # x divisions (length of pitch)
ROWS = 12  # y divisions (width of pitch)

_PASS_SET_PIECE = {"CornerTaken", "FreekickTaken", "IndirectFreekickTaken", "ThrowIn", "GoalKick"}


def cell_index(x: float | None, y: float | None) -> int:
    """Flat 0-191 cell index for a 0-100 coordinate (column-major: col*ROWS+row)."""
    col = min(COLS - 1, max(0, int((x or 0.0) / 100 * COLS)))
    row = min(ROWS - 1, max(0, int((y or 0.0) / 100 * ROWS)))
    return col * ROWS + row


def _grid() -> list[float]:
    from .xt_grid import GRID  # generated by scripts/fit_xt.py

    return GRID


def _is_set_piece_pass(event: dict) -> bool:
    return any(q["type"]["displayName"] in _PASS_SET_PIECE for q in event.get("qualifiers", []))


def _pass_moves(events: list[dict], player_id: int) -> list[tuple[float, float, float, float]]:
    """(start_x, start_y, end_x, end_y) for the player's successful open-play passes."""
    moves: list[tuple[float, float, float, float]] = []
    for e in events:
        if e["player_id"] != player_id or e["type_name"] != "Pass":
            continue
        if e["outcome_name"] != "Successful" or _is_set_piece_pass(e):
            continue
        ex = get_qualifier(e, "PassEndX")
        ey = get_qualifier(e, "PassEndY")
        sx, sy = e.get("x"), e.get("y")
        if ex is None or ey is None or sx is None or sy is None:
            continue
        moves.append((float(sx), float(sy), float(ex), float(ey)))
    return moves


def sum_action_value(
    moves: list[tuple[float, float, float, float]], grid: list[float]
) -> float:
    """Σ value(end_cell) − value(start_cell) over a list of moves."""
    total = 0.0
    for sx, sy, ex, ey in moves:
        total += grid[cell_index(ex, ey)] - grid[cell_index(sx, sy)]
    return round(total, 4)


def xt_pass(events: list[dict], player_id: int, grid: list[float] | None = None) -> float:
    return sum_action_value(_pass_moves(events, player_id), grid if grid is not None else _grid())


def xt_carry(events: list[dict], player_id: int, grid: list[float] | None = None) -> float:
    return sum_action_value(
        _derive_carries(events, player_id), grid if grid is not None else _grid()
    )


def xt_total(events: list[dict], player_id: int, grid: list[float] | None = None) -> float:
    g = grid if grid is not None else _grid()
    return round(xt_pass(events, player_id, g) + xt_carry(events, player_id, g), 4)
