"""Fit our own Expected Threat (xT) grid from stored events (SPEC §8.4.1).

Reads a sample of matches from Supabase Storage, accumulates per-cell shot /
goal / move statistics + a move transition matrix (successful open-play passes
and carries), and iterates the xT recurrence to convergence:

    xT[c] = P(shot|c)·P(goal|shot,c) + P(move|c)·Σ_c' T[c→c']·xT[c']

Writes the converged grid to src/stats/xt_grid.py (generated; do not hand-edit).

Usage:
  python scripts/fit_xt.py --limit 800
"""

import argparse
import datetime as dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.ingest.reprocess import iter_stored_matches
from src.parser.events import parse_events
from src.stats._qualifiers import get_qualifier, has_qualifier
from src.stats.carries import _derive_carries
from src.stats.goals import SHOT_TYPES
from src.stats.xt import COLS, ROWS, _is_set_piece_pass, cell_index

_N = COLS * ROWS
_OUT = Path(__file__).parent.parent / "src" / "stats" / "xt_grid.py"


def _accumulate(limit: int, competition_id: int | None) -> dict:
    actions = [0] * _N
    shots = [0] * _N
    goals = [0] * _N
    moves = [0] * _N
    trans: list[dict[int, int]] = [dict() for _ in range(_N)]
    n_matches = 0

    for item in iter_stored_matches(limit=limit, competition_id=competition_id):
        evs = parse_events(item["match_data"])
        n_matches += 1

        for e in evs:
            if e["type_name"] in SHOT_TYPES and not has_qualifier(e, "Penalty"):
                i = cell_index(e.get("x"), e.get("y"))
                shots[i] += 1
                actions[i] += 1
                if e["type_name"] == "Goal":
                    goals[i] += 1

        move_list: list[tuple[float, float, float, float]] = []
        for e in evs:
            if e["type_name"] == "Pass" and e["outcome_name"] == "Successful":
                if _is_set_piece_pass(e):
                    continue
                ex, ey = get_qualifier(e, "PassEndX"), get_qualifier(e, "PassEndY")
                sx, sy = e.get("x"), e.get("y")
                if ex is not None and ey is not None and sx is not None and sy is not None:
                    move_list.append((float(sx), float(sy), float(ex), float(ey)))
        for pid in {e["player_id"] for e in evs if e["player_id"] is not None}:
            move_list.extend(_derive_carries(evs, pid))

        for sx, sy, ex, ey in move_list:
            i = cell_index(sx, sy)
            j = cell_index(ex, ey)
            actions[i] += 1
            moves[i] += 1
            trans[i][j] = trans[i].get(j, 0) + 1

        if n_matches % 100 == 0:
            print(f"  accumulated {n_matches} matches")

    return {
        "actions": actions,
        "shots": shots,
        "goals": goals,
        "moves": moves,
        "trans": trans,
        "n_matches": n_matches,
    }


def _solve(acc: dict, max_iter: int = 500, tol: float = 1e-8) -> tuple[list[float], int]:
    actions, shots, goals, moves, trans = (
        acc["actions"],
        acc["shots"],
        acc["goals"],
        acc["moves"],
        acc["trans"],
    )
    shot_p = [shots[i] / actions[i] if actions[i] else 0.0 for i in range(_N)]
    goal_p = [goals[i] / shots[i] if shots[i] else 0.0 for i in range(_N)]
    move_p = [moves[i] / actions[i] if actions[i] else 0.0 for i in range(_N)]
    tnorm = [
        {j: c / moves[i] for j, c in trans[i].items()} if moves[i] else {} for i in range(_N)
    ]

    xt = [0.0] * _N
    iters = 0
    for iters in range(1, max_iter + 1):
        nxt = [0.0] * _N
        max_delta = 0.0
        for i in range(_N):
            move_val = 0.0
            for j, p in tnorm[i].items():
                move_val += p * xt[j]
            nxt[i] = shot_p[i] * goal_p[i] + move_p[i] * move_val
            max_delta = max(max_delta, abs(nxt[i] - xt[i]))
        xt = nxt
        if max_delta < tol:
            break
    return xt, iters


def _write_grid(grid: list[float], n_matches: int) -> None:
    today = dt.date.today().isoformat()
    body = (
        "# ruff: noqa: E501\n"
        '"""GENERATED by scripts/fit_xt.py — do not edit by hand.\n\n'
        f"Expected Threat grid ({COLS}x{ROWS}), fit on our own WhoScored events.\n"
        f"Trained {today} on {n_matches} matches. Attack toward x=100.\n"
        'Flat list indexed by src.stats.xt.cell_index (col*ROWS+row)."""\n\n'
        f"COLS = {COLS}\nROWS = {ROWS}\n\n"
        f"GRID = {[round(v, 6) for v in grid]}\n"
    )
    _OUT.write_text(body)


def _print_surface(grid: list[float]) -> None:
    print("\nxT surface (rows = x-thirds toward goal, value = mean over width):")
    for col in range(COLS):
        col_vals = [grid[col * ROWS + r] for r in range(ROWS)]
        bar = "#" * int(sum(col_vals) / ROWS * 400)
        print(f"  x-col {col:2d} (x~{col / COLS * 100:3.0f}-{(col + 1) / COLS * 100:3.0f}): "
              f"{sum(col_vals) / ROWS:.4f} {bar}")
    print(f"  min cell {min(grid):.5f}  max cell {max(grid):.5f}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Fit the xT grid from stored events.")
    ap.add_argument("--limit", type=int, default=800, help="matches to sample (default 800)")
    ap.add_argument("--competition", type=int, default=None, help="restrict sample to one comp")
    args = ap.parse_args()

    print(f"Sampling up to {args.limit} stored matches...")
    acc = _accumulate(args.limit, args.competition)
    grid, iters = _solve(acc)
    print(f"converged in {iters} iterations over {acc['n_matches']} matches")
    _print_surface(grid)
    _write_grid(grid, acc["n_matches"])
    print(f"\nwrote {_OUT}")


if __name__ == "__main__":
    main()
