"""Fit the production xG model and write src/stats/xg_coefficients.py.

Target: Understat's xG (soft label) — so output lands on the accepted xG scale.
Runtime: only WhoScored-derived features (see src/stats/xg_model.build_features).
Validation: 5-fold CV by match -> per-shot R^2 + per-player rank correlation.
Final coefficients are refit on ALL non-penalty shots.

Reproduce with:  python scripts/train_production_xg.py
(requires xg_training_data.json from scripts/fetch_training_data.py)
"""

import json
import math
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.stats.xg_model import CONTINUOUS_IDX, FEATURE_NAMES, build_features

DATA = Path(__file__).parent.parent / "xg_training_data.json"
OUT = Path(__file__).parent.parent / "src" / "stats" / "xg_coefficients.py"
N_FOLDS = 5

_SIT = {"OpenPlay": "open", "FromCorner": "corner", "SetPiece": "setpiece", "DirectFreekick": "dfk"}
_LA = {"Throughball": "throughball", "Cross": "cross", "Chipped": "chipped", "HeadPass": "headpass"}


def feats(s: dict) -> list[float]:
    return build_features(
        s["X"] * 100,
        s["Y"] * 100,
        s["shotType"] == "Head",
        _SIT.get(s["situation"], "open"),
        _LA.get(s.get("lastAction", ""), "pass"),
    )


def sigmoid(z: float) -> float:
    if z < -35:
        return 1e-15
    if z > 35:
        return 1 - 1e-15
    return 1.0 / (1.0 + math.exp(-z))


def fit(X, y, lr=0.3, iters=4000):
    n, k = len(X), len(X[0])
    mean = [0.0] * k
    std = [1.0] * k
    for j in CONTINUOUS_IDX:
        col = [r[j] for r in X]
        mean[j] = sum(col) / n
        std[j] = math.sqrt(sum((v - mean[j]) ** 2 for v in col) / n) or 1.0
    Xs = [[(r[j] - mean[j]) / std[j] if j in CONTINUOUS_IDX else r[j] for j in range(k)] for r in X]
    w = [0.0] * k
    b = 0.0
    for _ in range(iters):
        gw = [0.0] * k
        gb = 0.0
        for r, yi in zip(Xs, y):
            e = sigmoid(sum(w[j] * r[j] for j in range(k)) + b) - yi
            for j in range(k):
                gw[j] += e * r[j]
            gb += e
        for j in range(k):
            w[j] -= lr * gw[j] / n
        b -= lr * gb / n
    return w, b, mean, std


def predict(r, w, b, mean, std):
    z = b + sum(
        w[j] * ((r[j] - mean[j]) / std[j] if j in CONTINUOUS_IDX else r[j]) for j in range(len(r))
    )
    return sigmoid(z)


def pearson(a, b):
    n = len(a)
    ma, mb = sum(a) / n, sum(b) / n
    cov = sum((x - ma) * (y - mb) for x, y in zip(a, b))
    sa = math.sqrt(sum((x - ma) ** 2 for x in a))
    sb = math.sqrt(sum((y - mb) ** 2 for y in b))
    return cov / (sa * sb) if sa and sb else float("nan")


def ranks(v):
    order = sorted(range(len(v)), key=lambda i: v[i])
    r = [0.0] * len(v)
    for rk, i in enumerate(order):
        r[i] = rk
    return r


def main():
    raw = json.loads(DATA.read_text())
    shots = [s for s in raw if s["situation"] != "Penalty"]
    from collections import Counter

    print(f"{len(shots)} non-penalty shots, leagues: {dict(Counter(s['league'] for s in shots))}")

    X = [feats(s) for s in shots]
    y = [s["xG"] for s in shots]

    # ---- 5-fold CV by match for honest validation ----
    mids = sorted({(s["league"], s["match_id"]) for s in shots})
    fold = {m: i % N_FOLDS for i, m in enumerate(mids)}
    oof = [0.0] * len(shots)
    for f in range(N_FOLDS):
        trX, trY, te = [], [], []
        for i, s in enumerate(shots):
            if fold[(s["league"], s["match_id"])] == f:
                te.append(i)
            else:
                trX.append(X[i])
                trY.append(y[i])
        w, b, mn, sd = fit(trX, trY)
        for i in te:
            oof[i] = predict(X[i], w, b, mn, sd)

    mu = sum(y) / len(y)
    r2 = 1 - sum((p - u) ** 2 for p, u in zip(oof, y)) / sum((u - mu) ** 2 for u in y)
    print("\n== CV validation (out-of-fold) ==")
    print(f"  per-shot R^2 vs Understat xG   {r2:.3f}")
    print(f"  per-shot Pearson               {pearson(oof, y):.3f}")
    print(f"  sum xG  {sum(oof):.0f} pred  vs  {sum(y):.0f} understat")

    pp = {}
    for s, p in zip(shots, oof):
        a = pp.setdefault((s["league"], s["player"]), [0.0, 0.0])
        a[0] += p
        a[1] += s["xG"]
    keys = [k for k, v in pp.items() if v[1] >= 3.0]
    pf = [pp[k][0] for k in keys]
    pu = [pp[k][1] for k in keys]
    print(f"  per-player npxG ({len(keys)} players >=3.0): "
          f"Pearson {pearson(pf, pu):.3f}  Spearman {pearson(ranks(pf), ranks(pu)):.3f}")

    # ---- final coefficients on ALL data ----
    w, b, mean, std = fit(X, y)
    OUT.write_text(
        "# ruff: noqa: E501\n"
        '"""GENERATED by scripts/train_production_xg.py — do not edit by hand.\n\n'
        "Logistic xG coefficients fit by regression on Understat xG.\n"
        f"Trained {datetime.now(UTC):%Y-%m-%d} on {len(shots)} non-penalty shots "
        f"({len(mids)} matches, leagues {sorted(set(s['league'] for s in shots))}).\n"
        f"CV: per-shot R^2={r2:.3f}, per-player Spearman={pearson(ranks(pf), ranks(pu)):.3f}.\n"
        '"""\n\n'
        f"FEATURE_NAMES = {FEATURE_NAMES!r}\n\n"
        f"MEANS = {[round(v, 6) for v in mean]!r}\n\n"
        f"STDS = {[round(v, 6) for v in std]!r}\n\n"
        f"WEIGHTS = {[round(v, 6) for v in w]!r}\n\n"
        f"BIAS = {round(b, 6)!r}\n"
    )
    print(f"\nwrote {OUT.relative_to(Path(__file__).parent.parent)}")


if __name__ == "__main__":
    main()
